import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFile,access} from 'node:fs/promises';
import {readEntries} from '../scripts/build.mjs';
import {renderEntry,validateEntry,safeMediaPath} from '../scripts/content.mjs';
import {handle,createState,validState} from '../auth/worker.mjs';
const record={id:'test-entry',title:'测试',title_en:'Test',order:0,published:true,body:'第一段\n\n第二段',media:[]};
test('all content records validate and reference existing media',async()=>{const entries=await readEntries();assert.deepEqual(Object.keys(entries),['activities','ceremonies','members','relations']);for(const list of Object.values(entries))assert.ok(Array.isArray(list));});
test('plain text escapes executable HTML in all languages',()=>{const html=renderEntry({...record,title:'<img src=x onerror=alert(1)>',body_en:'<script>alert(1)</script>'},'activities');assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;img'));assert.ok(html.includes('&lt;script&gt;'));});
test('media paths reject traversal, remote files and executable types',()=>{for(const path of ['../../a','assets/../a','https://evil.test/a','assets/%2e%2e/a','assets/a?x','assets/a\\b'])assert.throws(()=>safeMediaPath(path));assert.throws(()=>validateEntry({...record,media:[{kind:'image',src:'assets/a.svg',alt:'x'}]},'activities'));});
test('blank English falls back to Chinese and multiline text keeps paragraphs',()=>{const html=renderEntry({...record,title_en:''},'activities');assert.match(html,/data-en="测试"/);assert.match(html,/<p>第一段<\/p><p>第二段<\/p>/);});
test('invalid content fails before publish',()=>{assert.throws(()=>validateEntry({...record,title:''},'members'));assert.throws(()=>validateEntry({...record,order:'0'},'activities'));assert.throws(()=>validateEntry({...record,id:'../escape'},'activities'));});
const env={GITHUB_CLIENT_ID:'test-client',GITHUB_CLIENT_SECRET:'test-secret',CMS_ORIGIN:'https://yangzhu.org',AUTH_ORIGIN:'https://auth.example.test',ALLOWED_USERS:'president'};
test('OAuth missing config fails closed',async()=>assert.equal((await handle(new Request(env.AUTH_ORIGIN+'/auth'),{})).status,503));
test('OAuth start pins callback and site, uses secure cookie',async()=>{const r=await handle(new Request(env.AUTH_ORIGIN+'/auth?provider=github&site_id=yangzhu.org'),env);assert.equal(r.status,302);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal(new URL(r.headers.get('location')).searchParams.get('redirect_uri'),env.AUTH_ORIGIN+'/callback');assert.equal((await handle(new Request(env.AUTH_ORIGIN+'/auth?provider=github&site_id=evil.test'),env)).status,400);});
test('OAuth state expires, rejects tampering and missing cookie',async()=>{const state=await createState(env.GITHUB_CLIENT_SECRET,1000);assert.ok(await validState(state,env.GITHUB_CLIENT_SECRET,2000));assert.equal(await validState(state,env.GITHUB_CLIENT_SECRET,602000),false);assert.equal(await validState(state+'x',env.GITHUB_CLIENT_SECRET,2000),false);assert.equal((await handle(new Request(env.AUTH_ORIGIN+'/callback?state='+state+'&code=x'),env)).status,403);});
async function callback(login='president',push=true){const state=await createState(env.GITHUB_CLIENT_SECRET);const request=new Request(env.AUTH_ORIGIN+'/callback?state='+state+'&code=x',{headers:{Cookie:'__Host-yangzhu-oauth='+state}});const fetcher=async url=>Response.json(url.endsWith('access_token')?{access_token:'test-token'}:url.endsWith('/user')?{login}:{permissions:{push}});return handle(request,env,fetcher);}
test('OAuth rejects uninvited accounts and read-only collaborators',async()=>{assert.equal((await callback('stranger')).status,403);assert.equal((await callback('president',false)).status,403);});
test('OAuth sends token only to exact CMS origin with protected response',async()=>{const r=await callback();assert.equal(r.status,200);const body=await r.text();assert.match(body,/e.origin!==target/);assert.match(body,/https:\/\/yangzhu.org/);assert.ok(!body.includes("postMessage('authorizing:github','*')"));assert.match(r.headers.get('content-security-policy'),/default-src 'none'/);assert.equal(r.headers.get('cache-control'),'no-store');});
